spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC
    username: root
    password: a2031291160

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


